### ISSUE TITLE
Associated AsBuilt module unavailable

### ISSUE THREAD

**Issue by ChoochTheAnimalSteel** [AsBuiltReport/AsBuiltReport.Microsoft.Azure#1]
Running the install module command:
Install-Module AsBuiltReport.Microsoft.Azure

Produces this error:
PackageManagement\Install-Package : No match was found for the specified search criteria and module name
'AsBuiltReport.Microsoft.Azure'.

Can not find this module with with Find-Module either.
Manual download is also unavailable.

System - Windows 10 21H2 (completely updated as of this writing)
PowerShell version - 5.1

**Comment by rebelinux** [comment]
I believe this report is not yet available in Powershell Gallery. Maybe you could try the manual installation procedure.

https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.Azure#github

**Comment by tpcarman** [comment]
Hi @ChoochTheAnimalSteel,

Long story short, I simply haven't had the time to publish this to the PowerShell Gallery as yet. I will try and get this published as soon as I can. In the meantime, and as @rebelinux has mentioned, you can follow the steps to download the module directly from GitHub.

**Comment by tpcarman** [comment]
FYI, I'm currently reviewing this module with plans to publish in the next week or so. I haven't worked on this module in about a year and it is need of some updates. Stay tuned!
