### ISSUE TITLE
No information in Report

### ISSUE THREAD

**Issue by TAThacker** [AsBuiltReport/AsBuiltReport.Microsoft.Azure#12]
### Bug description

Hi, i run the new-asbuiltreport as shown in the screenshot attached and it does not error or provide any warnings / errors from the verbose. It creates the report but all i can see if the report is the Subscription ID. Also see attached.

### Command-line input

 New-AsBuiltReport -Report Microsoft.Azure -Target 'xxxxx' -MFA -Format HTML,Word -OutputFolderPath 'C:\users\xxxxx\desktop\reports' -Timestamp -EnableHealthCheck -Verbose

### Steps to reproduce

Unsure

### Expected behaviour

I expected the report to show Virtual Machines and other information.

### Screenshots

![image](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.Azure/assets/139339696/2e262473-7d98-4dc9-811f-2cdef56e0e2b)
![image](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.Azure/assets/139339696/e34b9966-7ac2-409f-9c86-2ec9103e6c4f)

### Operating System

Windows 11

### PowerShell Version

Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### PowerShell Modules

Name                          Version
----                          -------
AsBuiltReport.Core            1.3.0
AsBuiltReport.Microsoft.Azure 0.1.5
PScribo                       0.10.0
AsBuiltReport.Microsoft.Azure 0.1.5

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).
- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this bug report.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Microsoft.Azure/issues) before submitting this bug report.

**Comment by TAThacker** [comment]
Hi, Any response on this one?

**Comment by tpcarman** [comment]
Silly question, but do you actually have resources deployed within the subscription? What role have you been assigned on the subscription?

**Comment by tpcarman** [comment]
Closing this issue due to a lack of response. Please reopen the issue if you are able to provide further information.
